on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: "Build & Release Medteem APK"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5'   # lock version
          channel: 'stable'

      # 4. Cache dependencies
      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-cache

      # 5. Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 6. Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # 7. Upload APK to GitHub Releases
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

# pull request on main master